Class DC_Hands : Fist
{
    Default
    {
        +WEAPON.NOALERT
    }

    States
	{
	Ready:
		PUNG A 1 A_WeaponReady;
		Loop;
	Deselect:
		PUNG A 1 A_Lower;
		Loop;
	Select:
		PUNG A 1 A_Raise;
		Loop;
	Fire:
		PUNG B 4;
		PUNG C 4 
        {
            let companyMan = CompanyMan(self);
            companyMan.ToggleItemActive();
        }
		PUNG D 5;
		PUNG C 4;
		PUNG B 5 A_ReFire;
		Goto Ready;
	}
}